version: "3.9"  # optional since v1.27.0
services:
  todoapi:
    container_name: todoapi
    build:
      context: ../../code/TodoApi
      dockerfile: ../../code/TodoApi/Dockerfile
    ports:
      - "8080:80"
    restart: always
  myapp:
    container_name: "myapp"
    build:
      context: ../../code/my-app
      dockerfile: ../../code/my-app/Dockerfile
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ../reverse_proxy
      dockerfile: ../reverse_proxy/Dockerfile
    ports:
      - 80:80
    depends_on:
      - todoapi
      - myapp
  authapi:
    container_name: authapi
    build:
      context: ../../code/auth
      dockerfile: ../../code/auth/Dockerfile
    ports:
      - "8082:81"
    restart: always
  authzapi:
    container_name: authzapi
    build:
      context: ../../code/authz
      dockerfile: ../../code/authz/Dockerfile
    ports:
      - "8081:82"
    restart: always