version: "3.9"  # optional since v1.27.0
services:
  TodoApi:
    container_name: TodoApi
    build:
      context: .
      dockerfile: ../../code/TodoApi/Dockerfile
    ports:
      - "8080:80"
    restart: always
  my-app:
    container_name: "my-app"
    build:
      context: .
      dockerfile: ../../code/my-app/Dockerfile
    ports:
      - "3000:3000"
    restart: always
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: .
      dockerfile: reverse_proxy/Dockerfile
    ports:
      - 80:80
    depends_on:
      - TodoApi
      - my-app